Re record button
voice-notes/web pull request #15
Opened 2020-08-26 15:52 UTC by Joanneyoung01

- add new 'status' state in App component ('not recorded', 'recording', 'recorded')
- show re-record button if status is 'recorded' 
- a user can click on re-rerecord > timer resets, and audio clip is overwritten 
- during re-recording status updates accordingly

- at the end of recording 'send' button appears next to re-record button
![Voice Note FE (3)](https://user-images.githubusercontent.com/38694448/91326446-42deff80-e7bc-11ea-88ef-d1cf682711df.png)

<img width="705" alt="Screenshot 2020-08-26 at 16 45 39" src="https://user-images.githubusercontent.com/38694448/91326480-4d00fe00-e7bc-11ea-9324-1f2067b46f27.png">

2020-08-26 16:11 UTC, Joanneyoung01 commented
![Voice Note FE (4)](https://user-images.githubusercontent.com/38694448/91328703-2b554600-e7bf-11ea-9a03-01587b7e012a.png)
Updated component flow for the front end

2020-08-26 17:11 UTC, benfurber requested changes
Lovely. Thanks for adding the image as well.

Main issues: 
* Naming of stuff
* The send button should definitely be green

2020-08-26 17:11 UTC, benfurber commented on src/components/App/App.module.css
> +.buttons {
This this styling for a button list or an individual button? In other words I'm not sure about the naming - either `button` or `button-list`.

2020-08-26 17:11 UTC, benfurber commented on src/components/Recorder/recorder.test.tsx
> +    );
While you're hear, can you add additional coverage please - i.e. the other conditions of this component.

2020-08-26 17:11 UTC, benfurber commented on src/components/Recorder/recorder.tsx
> +  onClickStatus: any;
No anys please! What should this be?

2020-08-26 17:11 UTC, benfurber commented on src/components/Recorder/recorder.tsx
> +  onClickStatus: any;
And how can that typing be kept dry?

2020-08-26 17:11 UTC, benfurber commented on src/components/App/App.tsx
> +  const [status, setRecordingStatus] = useState('not recorded');
I think status is too generic a name. Let's go with recordingStatus, then the states can be 'ready', 'recording' and 'recorded'.

2020-08-26 17:11 UTC, benfurber commented on src/components/App/App.tsx
> +          status={status}
Is there not duplication of logic going on here?

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  background-color: black;
Let's define what black means to us so we can more easily change it later.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  border-radius: 50px 50px 0 0;
I guess this is fine for the moment as we're not worrying about responsiveness, but 50px will be pretty big on mobile.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  padding: 7.5px;
Not sure about this .5 business.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.tsx
> +  }
Can this logic be switched around please: https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +.btn {
Whole words please. So button. Also send-button is good.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  color: #bd200c;
Let's get this colour defined elsewhere and called in.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  border: 0;
Why is this needed?

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.module.css
> +  padding: 0;
Why is this needed?

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.tsx
> +import { FiArrowRight } from 'react-icons/fi';
Do these imports need to be separate calls? How could you get this on one line?

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.tsx
> +  status: string;
This links to the above comment, this can be typed more strongly in a typescript-y way.

2020-08-26 17:11 UTC, benfurber commented on src/components/SendButton/sendButton.tsx
> +export const SendButton = ({ status }: Props) => {
I appreciate this is partly just from picked up conventions on the other components (which I could have picked up before). I have a preference for doing this:
```
export const SendButton = (props: Props) => {
  const { status } = props;

2020-09-09 08:22 UTC, benfurber commented on src/components/Recorder/recorder.tsx
> +}: Props) => {
I'd do this another way:
```js
export const Recorder = (props: Props) => {
  const { isRecording, onClickStatus, recordingStatus } = props;
  ...
```

2020-09-28 16:09 UTC, Joanneyoung01 commented
Recording status functionality fixed on the recording status

To do: Fix timer on recording to reset timer back to 00:00

2021-03-15 15:56 UTC, merged